create table tblLeagueTable(
	leagueID int not null,
	position int,
	teamName nvarchar(1024),
	leagueCaption nvarchar(1024),
	currentMatchday int,
	gamesPlayed int,
	points int,
	GF int,
	GA int,
	GD int,
	win int,
	loss int,
	draw int,
	homeGF int,
	homeGA int,
	homeWin int,
	homeLoss int,
	homeDraw int,
	awayGF int,
	awayGA int,
	awayWin int,
	awayLoss int,
	awayDraw int	
);